### ISSUE TITLE
Python error... but then works

### ISSUE THREAD

**Issue by geodrinx** [enricofer/go2streetview#11]
today, go2streetview returns this strange error, every time I take the yellow line

Traceback (most recent call last):
  File "C:/Users/rrr/.qgis2/python/plugins\go2streetview\go2streetview.py", line 215, in catchJSevents
    self.writeInfoBuffer(self.transformToCurrentSRS(actualPoint))
  File "C:/Users/rrr/.qgis2/python/plugins\go2streetview\go2streetview.py", line 497, in writeInfoBuffer
    if self.infoBoxManager.getInfolayer().geometryType() == QGis.Point:
AttributeError: 'NoneType' object has no attribute 'geometryType'

But... after some time the image appears correctly.

**Comment by geodrinx** [comment]
I discovered that the python panels are two

**Comment by geodrinx** [comment]
I restarted QGIS and it works, now   :)
