### ISSUE TITLE
go2streetview - Python Error

### ISSUE THREAD

**Issue by serloc** [enricofer/go2streetview#39]
Hi,
I'm trying to work with go2streetview plugin for my first time. But unluckly when I start the plugin and I click on the street coverage it carry out a python error and it don't work.
Could you help me?
Thank you.

ps. I'm trying with QGIS 3.2.3 and QGIS 2.18.24

**Comment by serloc** [comment]
This is the python error log:
2018-10-04T17:40:19	1	Traceback (most recent call last):
			  File "C:/Users/SERGIO/.qgis2/python/plugins\go2streetview\go2streetview.py", line 444, in catchJSevents
			    self.writeInfoBuffer(self.transformToCurrentSRS(actualPoint))
			  File "C:/Users/SERGIO/.qgis2/python/plugins\go2streetview\go2streetview.py", line 747, in writeInfoBuffer
			    if self.infoBoxManager.getInfolayer().geometryType() == QGis.Point:
			AttributeError: 'NoneType' object has no attribute 'geometryType'
