### ISSUE TITLE
Error upon install: unexpected type 'str'

### ISSUE THREAD

**Issue by pcav** [enricofer/go2streetview#58]
```
mpossibile caricare il plugin 'go2streetview' a causa di un errore chiamando il metodo classFactory() 

TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/__init__.py", line 34, in classFactory
    from .go2streetview import go2streetview
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/go2streetview.py", line 26, in 
    from .go2streetviewDialog import go2streetviewDialog, dumWidget,snapshotLicenseDialog, infobox
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/go2streetviewDialog.py", line 29, in 
    import resources_rc
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/resources_rc.py", line 1251, in 
    qInitResources()
  File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/resources_rc.py", line 1242, in qInitResources
    QtCore.qRegisterResourceData(0x01, qt_resource_struct,
TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str'
```

**Comment by marcobra** [comment]
Same here on Ubuntu 20.04.3 LTS and QGIS 3.22.3-Białowieża 
Revisione codice QGIS | 1628765ec7
Versione Qt | 5.12.8

**Comment by joaoponceleao** [comment]
Seems to be an issue with the qgis2web plugin. Try uninstalling qgis2web first.
