### ISSUE TITLE
Execution error on generation of panorama images

### ISSUE THREAD

**Issue by pantelis** [enricofer/go2streetview#65]
Hi and thank you for this excellent plugin. We are working in ortho maps to streetview synthesis system using ML and we need lots of training data. The ability of the plugin to create panorama snapshots is very useful in this respect but we are getting the following error. I wonder if this is a known problem or you can advise on a quick fix. 

----

An error has occurred while executing Python code: 

AttributeError: type object 'QgsWkbTypes' has no attribute 'WKBPoint' 
Traceback (most recent call last):
  File "/home/pantelis.monogioudis/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/snapshot.py", line 102, in returnAnnotationsValue
    self.saveShapeFile()
  File "/home/pantelis.monogioudis/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/snapshot.py", line 165, in saveShapeFile
    self.createShapefile(sfPath)
  File "/home/pantelis.monogioudis/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/snapshot.py", line 151, in createShapefile
    writer = core.QgsVectorFileWriter(path, "ISO 8859-1", fields,  core.QgsWkbTypes.WKBPoint, srs, "ESRI Shapefile")
AttributeError: type object 'QgsWkbTypes' has no attribute 'WKBPoint'

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0] 
QGIS version: 3.24.3-Tisler Tisler, cf22b74e01

**Comment by enricofer** [comment]
fixed https://github.com/enricofer/go2streetview/commit/fc637fe80954fb9be92177956fa8b475fc10c7da
