### ISSUE TITLE
Qgis 'go2streetView' plugin: error message (Qubuntu)

### ISSUE THREAD

**Issue by image80** [enricofer/go2streetview#75]
I work with Qubuntu. I installed qgis 3.32.2-Lima. I have installed the latest version of the go2streetview plugin. I requested, got and set this Google API key into the plugin window.

You can see all usefull screen shots/photos here :  https://gis.stackexchange.com/questions/468355/qgis-go2streetview-plugin-error-message-qubuntu

When I use the plugin, I get an error message in the plugin window saying "small problem...an error has occurred. I paste below  various messages reported in the qgis logs console. I replace the value of the google key with XXXXXXXXXXXXXXXXX :

**Logs general Menu :**

```
Code:
    2023-10-13T08:48:28     INFO    État de l'application
                 variable d'environnement QGIS_PREFIX_PATH : 
                 Préfixe: /usr
                 Chemin des extensions: /usr/lib/qgis/plugins
                 Chemin des paquets de données: /usr/share/qgis
                 Nom du thème actif: default
                 Chemin du thème actif: /usr/share/qgis/resources/themes/default/icons/
                 Chemin du thème par défaut: :/images/themes/default/
                 Chemins de recherche SVG: /usr/share/qgis/svg/
                  /home/geoteca/.local/share/QGIS/QGIS3/profiles/default/svg/
                 Chemin de la BD utilisateur: /usr/share/qgis/resources/qgis.db
                 Chemin de la BD d'authentification: /home/geoteca/.local/share/QGIS/QGIS3/profiles/default/qgis-auth.db
```

**Logs go2streetview Menu :**
```
Code:
2023-10-13T09:34:04     INFO    file:///home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/res/g2sv.html?lat=14.748027087080024&long=-17.383023740224072&width=444&height=519&heading=0&APIkey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
2023-10-13T09:34:04     INFO    file:///home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/res/g2gm.html?lat=14.748027087080024&long=-17.383023740224072&wi[1]dth=444&height=519&zoom=19&heading=0&APIkey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Logs python Menu :**
```
Code:
2023-10-13T09:36:38     WARNING    Traceback (most recent call last):
              File "/home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/go2streetview.py", line 534, in openInBrowserAction
              self.openInBrowserSV()
              File "/home/geoteca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/go2streetview.py", line 754, in openInBrowserSV
              pitch = str(-1 * math.floor(float(p['pitch'])))
             KeyError: 'pitch'

```

**Logs general Menu :**
```
Code:
2023-10-13T09:36:39     WARNING    Erreur Python : Une erreur est survenue lors de l'exécution du code Python : Voir le journal des erreurs Python pour plus de détails
```

Thanks so much for your usefull help.
Kind regards.

**Comment by enricofer** [comment]
This is not a plugin issue. It's an API error.
You should check in [console.developers.google.com ](https://console.cloud.google.com) if the API is correctly running and activated. Furthermore you should check if the API key is correctly inserted in about dialog 
![Schermata da 2023-10-13 14-58-16](https://github.com/enricofer/go2streetview/assets/7544963/6e49c55d-d64d-4832-8ec8-72aa0cabcdb8)

**Comment by image80** [comment]
Thanks for your reply @enricofer 
When i go on the console,  The API seems activited. 
i paste below the screen shot. And, i double checked, i set/inserted correctly the API key in about dialog. Unfortunaltly, i'm still facing to the same error message.

![SS_googlePlatform](https://github.com/enricofer/go2streetview/assets/7910636/3eb10ac5-01fb-4742-8202-f069b8821293)

**Comment by image80** [comment]
After a new check. You right. i did not validate the Maps JavaScript API. And now, the plugin works well. Thanks so much.

**Comment by AndreaBaro** [comment]
Ciao Enrico,
anche a me da un paio di giorni il plugin non funziona più. Prima è sempre stato perfetto (e utilissimo).
Sono su Qgis 3.28.12 in ambiente Windows. Ho verificato l'attivazione delle API e quelle per le mappe sono tutte attivate. Ho anche provato a reinstallare il plugin, ma nulla da fare.
A me pare che non dipenda dal plugin, ma da qualche modifica di google: anche la mia collega che usa qgis/go2streetview ha il medesimo problema.
Grazie (per l'attenzione e per il plugin)
