### ISSUE TITLE
Errore importazione QtWebEngineWidgets

### ISSUE THREAD

**Issue by sitSV** [enricofer/go2streetview#94]
Impossibile caricare il plugin 'go2streetview' a causa di un errore chiamando il metodo classFactory() 

ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (C:\PROGRA~1\QGIS33~2.1\apps\Python312\Lib\site-packages\PyQt5\__init__.py). Did you mean: 'QtWebKitWidgets'? 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~2.1/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/rruggeri.URBANISTICA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview\__init__.py", line 34, in classFactory
    from .go2streetview import go2streetview
  File "C:\PROGRA~1/QGIS33~2.1/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/rruggeri.URBANISTICA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview\go2streetview.py", line 22, in 
    from PyQt5 import Qt, QtCore, QtWidgets, QtGui, QtWebEngineWidgets, QtXml, QtNetwork, uic
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (C:\PROGRA~1\QGIS33~2.1\apps\Python312\Lib\site-packages\PyQt5\__init__.py). Did you mean: 'QtWebKitWidgets'?

Versione Python: 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
Versione di QGIS: 3.38.1-Grenoble Grenoble, 3d4177afc6 

Percorso Python:
C:\Users/rruggeri.URBANISTICA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\TAF-to-CSV-main
C:\Users/rruggeri.URBANISTICA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\MultiMaps
C:\Users/rruggeri.URBANISTICA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HTML_Generator-main
C:\Users\rruggeri.URBANISTICA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gistools/libs
C:\Users\rruggeri.URBANISTICA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gistools/apps
C:\Users\rruggeri.URBANISTICA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gistools/gui
C:\Users\rruggeri.URBANISTICA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\gistools
C:/PROGRA~1/QGIS33~2.1/apps/qgis/./python
C:/Users/rruggeri.URBANISTICA/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/rruggeri.URBANISTICA/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~2.1/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~2.1\apps\grass\grass83\etc\python
C:\Users\rruggeri.URBANISTICA\Documents
C:\Program Files\QGIS 3.38.1\bin\python312.zip
C:\PROGRA~1\QGIS33~2.1\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~2.1\apps\Python312\Lib
C:\Program Files\QGIS 3.38.1\bin
C:\PROGRA~1\QGIS33~2.1\apps\Python312
C:\PROGRA~1\QGIS33~2.1\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~2.1\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~2.1\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~2.1\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/rruggeri.URBANISTICA/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\rruggeri.URBANISTICA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res
C:\Users\rruggeri.URBANISTICA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\rruggeri.URBANISTICA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\postgisQueryBuilder
C:\Users\rruggeri.URBANISTICA\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\postgisQueryBuilder\extlibs
.
C:/DBT/PROGETTI QGIS/GW_SAVONA

**Comment by enricofer** [comment]
https://github.com/enricofer/go2streetview?tab=readme-ov-file#v100-from-qgis-336

Il giorno mer 24 lug 2024 alle ore 12:07 sitSV ***@***.***>
ha scritto:

**Comment by ChrisHills463** [comment]
For fedora 42:-

```bash
sudo dnf install python3-qt5-webengine
```
