### ISSUE TITLE
Fails to install?  Error when calling its classFactory() method 

### ISSUE THREAD

**Issue by kylesomerville** [enricofer/go2streetview#96]
Couldn't load plugin 'go2streetview' due to an error when calling its classFactory() method 

ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (C:\OSGeo4W\apps\Python312\Lib\site-packages\PyQt5\__init__.py). Did you mean: 'QtWebKitWidgets'? 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/kyle/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview\__init__.py", line 34, in classFactory
    from .go2streetview import go2streetview
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/kyle/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview\go2streetview.py", line 22, in 
    from PyQt5 import Qt, QtCore, QtWidgets, QtGui, QtWebEngineWidgets, QtXml, QtNetwork, uic
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (C:\OSGeo4W\apps\Python312\Lib\site-packages\PyQt5\__init__.py). Did you mean: 'QtWebKitWidgets'?

QGIS installed via OSGEO installer, unsure if this is a plugin bug or an error with my installation?

**Comment by enricofer** [comment]
#97
